### ISSUE TITLE
Error when running ILP.sh. Maybe the pretrained model weights are wrong?

### ISSUE THREAD

**Issue by a-little-hoof** [Tianshi-Xu/PrivCirNet#1]
@Tianshi-Xu Hi, thank you for providing such a comprehensive codebase. 

But while I was running ILP.sh, I came across this error:
RuntimeError: Error(s) in loading state_dict for ViTLite:
	Missing key(s) in state_dict: "classifier.blocks.0.pre_norm.running_mean", "classifier.blocks.0.pre_norm.running_var", "classifier.blocks.0.norm1.running_mean", "classifier.blocks.0.norm1.running_var", "classifier.blocks.1.pre_norm.running_mean", "classifier.blocks.1.pre_norm.running_var", "classifier.blocks.1.norm1.running_mean", "classifier.blocks.1.norm1.running_var", "classifier.blocks.2.pre_norm.running_mean", "classifier.blocks.2.pre_norm.running_var", "classifier.blocks.2.norm1.running_mean", "classifier.blocks.2.norm1.running_var", "classifier.blocks.3.pre_norm.running_mean", "classifier.blocks.3.pre_norm.running_var", "classifier.blocks.3.norm1.running_mean", "classifier.blocks.3.norm1.running_var", "classifier.blocks.4.pre_norm.running_mean", "classifier.blocks.4.pre_norm.running_var", "classifier.blocks.4.norm1.running_mean", "classifier.blocks.4.norm1.running_var", "classifier.blocks.5.pre_norm.running_mean", "classifier.blocks.5.pre_norm.running_var", "classifier.blocks.5.norm1.running_mean", "classifier.blocks.5.norm1.running_var", "classifier.blocks.6.pre_norm.running_mean", "classifier.blocks.6.pre_norm.running_var", "classifier.blocks.6.norm1.running_mean", "classifier.blocks.6.norm1.running_var", "classifier.norm.running_mean", "classifier.norm.running_var". 

Maybe I loaded the wrong pre-trained model weights? I was trying to run _CirILP.py_ with config _configs/datasets/ViT/cifar10_ILP.yml_. I also downloaded the pre-trained model weights from the _pretrained_ directory, named "vit_c10.pth.tar". 

I couldn't figure out why so I'm commenting to ask for help. Thank you!

**Comment by Tianshi-Xu** [comment]
Hi, thanks for your attention to our work! I fix the bug and it works now. Thanks for pointing out the problem!

**Comment by a-little-hoof** [comment]
Thank you for your help! The problem is solved.
