### ISSUE TITLE
方便留您个联系方式吗？请教模型量化文章图的问题？

### ISSUE THREAD

**Issue by liuyiming199721** [Tianshi-Xu/PrivCirNet#2]

**Comment by Tianshi-Xu** [comment]
您好，您可以把问题在这里描述一下，因为我不确定有没有跑过图相关的算法

**Comment by liuyiming199721** [comment]
![微信图片_20241205115543](https://github.com/user-attachments/assets/896e416a-8934-4902-9edf-e75cd28021bf)
![微信图片_20241205115549](https://github.com/user-attachments/assets/1eb5ca67-c664-409c-ae0d-aec8c0370abf)
![微信图片_20241205115557](https://github.com/user-attachments/assets/3ed439c7-252b-48a5-a133-c2831e586bf7)
这三张图的代码可否开源一下代码谢谢

**Comment by Tianshi-Xu** [comment]
实验的图片由于涉及到组内其他同学的代码，暂时无法开源。不过，这些信息应该会有帮助：

- 图片是用matplotlib的折线图和柱状图画的。
- 图里如1.4x的标注、题注等是单独在powerpoint软件里手动添加上的。
